<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Matgar.Domain\Matgar.Domain.csproj" />
    <ProjectReference Include="..\Matgar.Infrastructure\Matgar.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Common\" />
    <Folder Include="Abstractions\" />
  </ItemGroup>

</Project>
